#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

# if [ $FEDORA_BRANCH = "rawhide" ] then;
	FEDORAVER=$(curl https://mirrors.rit.edu/fedora/fedora/linux/development/rawhide/COMPOSE_ID)
# else
#	FEDORAVER=$(curl https://mirrors.rit.edu/fedora/fedora/linux/releases/$FEDORA_BRANCH/COMPOSE_ID)
# fi

mkdir -p "$CADMIUMROOT/tmp"

# if [ $FEDORA_BRANCH = "rawhide" ] then;
	ROOTFS_RAW="https://mirrors.rit.edu/fedora/fedora/linux/development/rawhide/Workstation/aarch64/images/$FEDORAVER.aarch64.raw.xz"
# else
#	ROOTFS_TAR="https://mirrors.rit.edu/fedora/fedora/linux/development/rawhide/Workstation/aarch64/images/Fedora-Workstation-Rawhide-20230320.n.0.aarch64.raw.xz"
# fi

URL="$ROOTFS_RAW"
XZFILE="$(basename $URL)"
FILE="${XZFILE%.xz}"
DIR="$DESTDIR/tmp/fedora"
DEST="${XZFILE%-sda.raw.xz}.tar.xz"

[[ $UID -le 0 ]] || exit 1
[[ ! -f "$FILE" && ! -f "$XZFILE" ]] && curl -#kLO "$URL"
[[ ! -f "$FILE" ]] && unxz "$XZFILE"

mountpoint "$DIR" || {
  losetup -frP "$FILE"
  mkdir -p "$DIR"
  mount -L "_/"     "$DIR"
  mount -L "_/boot" "$DIR/boot"
  mountpoint "$DIR" || exit 2
}

export XZ_DEFAULTS="-T0"
tar -cvpJf "$DEST" -C "$DIR" --selinux --acls --xattrs --numeric-owner --exclude="lost+found" .

umount -fR "$DIR"
rmdir "$DIR"
losetup -D

$chroot $DESTDIR $qemu /usr/bin/dnf update --refresh -y

rm $DESTDIR/etc/resolv.conf # resolv.conf -> /run/systemd/resolve/resolv.conf not working in $chroot
echo "nameserver 1.1.1.1" > $DESTDIR/etc/resolv.conf # TODO: make it configurable or fetch from host?

$chroot $DESTDIR $qemu /usr/bin/dnf install networkmanager -y

$chroot $DESTDIR $qemu systemctl start NetworkManager.service
$chroot $DESTDIR $qemu systemctl enable NetworkManager.service
