#!/bin/bash
set -x
set -e

CADMIUMROOT="$(dirname $(dirname $(dirname $(realpath $0))))"
DESTDIR="$1"

. $CADMIUMROOT/config

 if [ $FEDORA_BRANCH = "development" ]; then
	FEDORAVER=$(curl --silent https://mirrors.rit.edu/fedora/fedora/linux/development/$FEDORA_RELEASE/Workstation/aarch64/images/ | grep -oP '"\K[^"\047]+(?=["\047])' | grep Fedora-Workstation-Rawhide | grep xz | head -1)
 else
	FEDORAVER=$(curl --silent https://mirrors.rit.edu/fedora/fedora/linux/releases/$FEDORA_RELEASE/Workstation/aarch64/images/ | grep -oP '"\K[^"\047]+(?=["\047])' | grep Fedora-Workstation-37 | grep xz | head -1)
 fi

mkdir -p "$CADMIUMROOT/tmp"

 if [ $FEDORA_BRANCH = "development" ]; then
	ROOTFS_RAW="https://mirrors.rit.edu/fedora/fedora/linux/development/$FEDORA_RELEASE/Workstation/aarch64/images/$FEDORAVER"
 else
	ROOTFS_RAW="https://mirrors.rit.edu/fedora/fedora/linux/releases/$FEDORA_RELEASE/Workstation/aarch64/images/$FEDORAVER"
 fi

# convert raw.xz to tar.xz

URL="$ROOTFS_RAW"
XZFILE="$(basename $ROOTFS_RAW)"
FILE="${XZFILE%.xz}"
DIR="$CADMIUMROOT/tmp/fedora"
DEST="${XZFILE%-sda.raw.xz}.tar.xz"

[[ $UID -le 0 ]] || exit 1
[[ ! -f "$FILE" && ! -f "$XZFILE" ]] && curl -#kLO "$URL"
[[ ! -f "$FILE" ]] && unxz "$XZFILE"

mountpoint "$DIR" || {
  losetup -frP "$FILE"
  mkdir -p "$DIR"
  mount -L "_/"     "$DIR"
  mount -L "_/boot" "$DIR/boot"
  mountpoint "$DIR" || exit 2
}

export XZ_DEFAULTS="-T0"
tar -cvpJf "$DEST" -C "$DIR" --selinux --acls --xattrs --numeric-owner --exclude="lost+found" .

umount -fR "$DIR"
rmdir "$DIR"
losetup -D

tar xfp $CADMIUMROOT/tmp/$DEST -C $DESTDIR

rm $DESTDIR/etc/resolv.conf # resolv.conf -> /run/systemd/resolve/resolv.conf not working in $chroot
echo "nameserver 1.1.1.1" > $DESTDIR/etc/resolv.conf # TODO: make it configurable or fetch from host?

$chroot $DESTDIR $qemu /usr/bin/dnf update --refresh -y
$chroot $DESTDIR $qemu /usr/bin/dnf install networkmanager -y

$chroot $DESTDIR $qemu systemctl start NetworkManager.service
$chroot $DESTDIR $qemu systemctl enable NetworkManager.service